version: "3.9"
services:
  redis:
    image: redis
    volumes: 
      - redis:/data
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      NUM_THREADS: 4
volumes:
  redis:
    driver: local
